behaviors:  
  RecommendContent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 32
      buffer_size: 4000
      learning_rate: 0.0005
      beta: 0.01
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 1
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 10
    max_steps: 10e6
    time_horizon: 1
    summary_freq: 100
    threaded: true
environment_parameters:
  block_offset:
      curriculum:
        - name: Lesson0
        completion_criteria:
          measure : reward
          signal_smoothing : true
          min_lesson_length : 100
          thresholds: 0.3
        value: 3
        - name: Lesson1
        completion_criteria:
          measure : reward
          signal_smoothing : true
          min_lesson_length : 100
          thresholds: 0.5
        value: 5
        - name: Lesson2
        value: 7