behaviors:
  RecommendContent:
    trainer_type: sac
    hyperparameters:
      batch_size: 512
      buffer_size: 81920
      learning_rate: 0.00005
      init_entcoef: 1
      buffer_init_steps: 10000
      save_replay_buffer: true
      learning_rate_schedule: constant
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 3
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      curiosity:
        strength: 0.9
        gamma: 0.99
        learning_rate: 0.00001
    keep_checkpoints: 10
    max_steps: 10e6
    time_horizon: 32
    summary_freq: 100
    threaded: true